#!/bin/bash
for s in     /usr/lib64/sox/libsox_fmt_alsa.so \
    /usr/lib64/sox/libsox_fmt_ao.so \
    /usr/lib64/sox/libsox_fmt_caf.so \
    /usr/lib64/sox/libsox_fmt_fap.so \
    /usr/lib64/sox/libsox_fmt_ffmpeg.so \
    /usr/lib64/sox/libsox_fmt_flac.so \
    /usr/lib64/sox/libsox_fmt_gsm.so \
    /usr/lib64/sox/libsox_fmt_lpc10.so \
    /usr/lib64/sox/libsox_fmt_mat4.so \
    /usr/lib64/sox/libsox_fmt_mat5.so \
    /usr/lib64/sox/libsox_fmt_mp3.so \
    /usr/lib64/sox/libsox_fmt_oss.so \
    /usr/lib64/sox/libsox_fmt_paf.so \
    /usr/lib64/sox/libsox_fmt_pulseaudio.so \
    /usr/lib64/sox/libsox_fmt_pvf.so \
    /usr/lib64/sox/libsox_fmt_sd2.so \
    /usr/lib64/sox/libsox_fmt_sndfile.so \
    /usr/lib64/sox/libsox_fmt_vorbis.so \
    /usr/lib64/sox/libsox_fmt_w64.so \
    /usr/lib64/sox/libsox_fmt_wavpack.so \
    /usr/lib64/sox/libsox_fmt_xi.so; do

	a=${s##*/}
	f=`echo $s | sed s!/usr/lib64!%_libdir!`
	name=`echo ${a%%.so} | tr '_' '-'`
	echo "Requires: $name = %version-%release"
	cat  > specs/$name.spec <<__EOF__
Summary: %summary
Group: Sound

%files
$f
__EOF__
done
